from transformers import Trainer as TransformersTrainer
from transformers import TrainingArguments as TransformersTrainingArguments

from trainer import Trainer
from training_args import TrainingArguments